Office
cacticouncil/simcoast pull request #23
Opened 2024-12-10 04:50 UTC by rafaela-eacf

Hey guys! This is a combined pr between Dev and I. Here are a few things that we added, so that you can test them:
- office scene, with clickable character, computer, and phone
   - computer displays unlocked sensors data
   - phone displays unlocked characters
   - added tutorial to lab
- lab scene with clickable character
   - cleaned up more information from shop and lab tutorial
Let us know if you guys can find any bugs or UI issues we might have missed!

2024-12-12 21:22 UTC, devp4 commented
Thanks for merging my branch in!

The only issue im facing is I cant buy sensors from the shop anymore. 

Nice job!

2024-12-12 22:02 UTC, rafaela-eacf commented
Hey Dev, would you mind explaining or screenshotting your issue please? I can't replicate it. I can still buy and place sensors from the shop :(

2024-12-12 22:39 UTC, devp4 approved these changes
Nevermind, restarting godot solved it!

2024-12-12 23:38 UTC, emenello requested changes
Hi Rafaela, just wanted to put in my review that I mentioned in the meeting. The bug happens on New Game. I ran through the tutorial then exit the Office scene. Then if you try to re-enter the office scene, the error happens. I think it has to do with not having a dialogue object for that instance, but still calling it because the office scene was clicked. I'd have to look into it but just having a default dialogue object per character might fix it for now?

2024-12-12 23:47 UTC, rafaela-eacf commented
Thank you Eddie. It was exactly what you said. Should be fixed now :)

2024-12-13 00:16 UTC, carlsuarez approved these changes
Looks good! Glad to see you figured out adding a tutorial segment.

2024-12-16 20:28 UTC, emenello approved these changes
Looks good! Good job on the fix!

2025-01-27 21:06 UTC, merged